In [1]:
import pandas as pd
import numpy as np

In [8]:
ticker_date_range = pd.read_csv('sp500_ticker_start_end.csv')

print(len(ticker_date_range.ticker))
print(len(ticker_date_range.ticker.unique()))

1230
1181

In [13]:
sp500 = pd.read_csv('sp500.csv')
sp500.head()

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989

In [14]:
sp500.columns = ['ticker', 'security', 'gics_sector', 'gics_sub_industry', 'location' , 'date_added', 'cik', 'founded']

In [17]:
sp500.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ticker             503 non-null    object
 1   security           503 non-null    object
 2   gics_sector        503 non-null    object
 3   gics_sub_industry  503 non-null    object
 4   location           503 non-null    object
 5   date_added         503 non-null    object
 6   cik                503 non-null    int64
 7   founded            503 non-null    object
dtypes: int64(1), object(7)
memory usage: 31.6+ KB

In [15]:
sp500_merge = ticker_date_range.merge(sp500, on='ticker', how='left')
sp500_merge

,ticker,start_date,end_date,security,gics_sector,gics_sub_industry,location,date_added,cik,founded
0,A,2000-06-05,NaN,Agilent Technologies,Health Care,Life Sciences Tools & Services,"Santa Clara, California",2000-06-05,1090872.0,1999
1,AABA,1999-12-08,2017-06-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AAL,1996-01-02,1997-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AAL,2015-03-23,2024-09-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AAMRQ,1996-01-02,2003-03-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1225,YUM,1997-10-07,NaN,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061.0,1997
1226,ZBH,2001-08-07,NaN,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869.0,1927
1227,ZBRA,2019-12-23,NaN,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212.0,1969
1228,ZION,2001-06-25,2024-03-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1229,ZTS,2013-06-24,NaN,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280.0,1952

In [24]:
# sp500_merge.groupby('ticker').count()
pd.set_option('display.max_rows', None)     # 모든 행 출력
pd.set_option('display.max_columns', None)  # 모든 열 출력

sp500_merge.sort_values(by=['ticker']).groupby('ticker').filter(lambda x: len(x) > 1)

,ticker,start_date,end_date,security,gics_sector,gics_sub_industry,location,date_added,cik,founded
2,AAL,1996-01-02,1997-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AAL,2015-03-23,2024-09-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,AMD,1996-01-02,2013-09-23,Advanced Micro Devices,Information Technology,Semiconductors,"Santa Clara, California",2017-03-20,2488.0,1969
59,AMD,2017-03-20,NaN,Advanced Micro Devices,Information Technology,Semiconductors,"Santa Clara, California",2017-03-20,2488.0,1969
65,AMP,2005-10-03,NaN,Ameriprise Financial,Financials,Asset Management & Custody Banks,"Minneapolis, Minnesota",2005-10-03,820027.0,1894
64,AMP,1996-01-02,1999-04-05,Ameriprise Financial,Financials,Asset Management & Custody Banks,"Minneapolis, Minnesota",2005-10-03,820027.0,1894
69,AN,1996-01-02,1999-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,AN,2003-02-24,2017-08-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,BR,1996-01-02,2006-04-03,Broadridge Financial Solutions,Industrials,Data Processing & Outsourced Services,"Lake Success, New York",2018-06-18,1383312.0,1962
169,BR,2018-06-18,NaN,Broadridge Financial Solutions,Industrials,Data Processing & Outsourced Services,"Lake Success, New York",2018-06-18,1383312.0,1962
195,CBE,1996-01-02,2009-09-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,CBE,2011-11-23,2012-12-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN
205,CCI,1996-01-02,1998-10-08,Crown Castle,Real Estate,Telecom Tower REITs,"Houston, Texas",2012-03-14,1051470.0,1994
206,CCI,2012-03-13,NaN,Crown Castle,Real Estate,Telecom Tower REITs,"Houston, Texas",2012-03-14,1051470.0,1994
214,CE,2001-04-02,2004-02-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
215,CE,2018-12-24,2025-04-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216,CEG,1996-01-02,2012-03-13,Constellation Energy,Utilities,Electric Utilities,"Baltimore, Maryland",2022-02-02,1868275.0,1999
217,CEG,2022-02-02,NaN,Constellation Energy,Utilities,Electric Utilities,"Baltimore, Maryland",2022-02-02,1868275.0,1999
222,CF,2000-06-19,2004-09-01,CF Industries,Materials,Fertilizers & Agricultural Chemicals,"Deerfield, Illinois",2008-08-27,1324404.0,1946
223,CF,2008-08-27,NaN,CF Industries,Materials,Fertilizers & Agricultural Chemicals,"Deerfield, Illinois",2008-08-27,1324404.0,1946
257,CNC,2016-03-30,NaN,Centene Corporation,Health Care,Managed Health Care,"St. Louis, Missouri",2016-03-30,1071739.0,1984
256,CNC,1997-01-15,2002-07-25,Centene Corporation,Health Care,Managed Health Care,"St. Louis, Missouri",2016-03-30,1071739.0,1984
275,COV,2007-07-02,2009-06-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
276,COV,2011-03-01,2015-01-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
274,COV,1996-01-02,1996-08-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
321,DD,1996-01-02,2017-09-01,DuPont,Materials,Specialty Chemicals,"Wilmington, Delaware",2019-06-03,1666700.0,2017 (1802)
322,DD,2019-06-03,NaN,DuPont,Materials,Specialty Chemicals,"Wilmington, Delaware",2019-06-03,1666700.0,2017 (1802)
329,DELL,1996-09-06,2013-10-29,Dell Technologies,Information Technology,"Technology Hardware, Storage & Peripherals","Round Rock, Texas",2024-09-23,1571996.0,2016
330,DELL,2024-09-23,NaN,Dell Technologies,Information Technology,"Technology Hardware, Storage & Peripherals","Round Rock, Texas",2024-09-23,1571996.0,2016
334,DG,2012-12-03,NaN,Dollar General,Consumer Staples,Consumer Staples Merchandise Retail,"Goodlettsville, Tennessee",2012-12-03,29534.0,1939
333,DG,1998-07-16,2007-07-09,Dollar General,Consumer Staples,Consumer Staples Merchandise Retail,"Goodlettsville, Tennessee",2012-12-03,29534.0,1939
354,DOW,1996-01-02,2017-09-01,Dow Inc.,Materials,Commodity Chemicals,"Midland, Michigan",2019-04-01,1751788.0,2019 (1897)
355,DOW,2019-04-02,NaN,Dow Inc.,Materials,Commodity Chemicals,"Midland, Michigan",2019-04-01,1751788.0,2019 (1897)
367,DXC,1996-01-02,2015-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
368,DXC,2017-04-04,2023-10-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
402,EQT,2022-10-03,NaN,EQT Corporation,Energy,Oil & Gas Exploration & Production,"Pittsburgh, Pennsylvania",2022-10-03,33213.0,1888
401,EQT,2008-12-19,2018-11-13,EQT Corporation,Energy,Oil & Gas Exploration & Production,"Pittsburgh, Pennsylvania",2022-10-03,33213.0,1888
407,ESV,2007-01-04,2009-12-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408,ESV,2012-07-31,2016-03-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
447,FL,1996-01-02,1999-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN
448,FL,2016-04-04,2019-08-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,FMC,1996-01-02,2002-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456,FMC,2009-08-19,2025-04-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
470,FSLR,2009-10-16,2017-03-20,First Solar,Information Technology,Semiconductors,"Tempe, Arizona",2022-12-19,1274494.0,1999
471,FSLR,2022-12-19,NaN,First Solar,Information Technology,Semiconductors,"Tempe, Arizona",2022-12-19,1274494.0,1999
480,GAS,1996-01-02,2011-12-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
481,GAS,2011-12-13,2016-07-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
492,GGP,2007-07-02,2008-11-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,GGP,2013-12-10,2018-08-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528,H,2006-08-01,2007-04-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
527,H,1996-01-02,2001-06-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
535,HCA,1996-01-02,2006-11-20,HCA Healthcare,Health Care,Health Care Facilities,"Nashville, Tennessee",2015-01-27,860730.0,1968
536,HCA,2015-01-27,NaN,HCA Healthcare,Health Care,Health Care Facilities,"Nashville, Tennessee",2015-01-27,860730.0,1968
549,HLT,1996-01-02,2007-10-25,Hilton Worldwide,Consumer Discretionary,"Hotels, Resorts & Cruise Lines","Tysons Corner, Virginia",2017-06-19,1585689.0,1919
550,HLT,2017-06-19,NaN,Hilton Worldwide,Consumer Discretionary,"Hotels, Resorts & Cruise Lines","Tysons Corner, Virginia",2017-06-19,1585689.0,1919
558,HP,1996-01-02,1999-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN
559,HP,2010-03-01,2020-05-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
566,HRS,1996-01-02,1999-11-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN
567,HRS,2008-09-22,2019-06-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
598,IR,1996-01-02,2009-07-01,Ingersoll Rand,Industrials,Industrial Machinery & Supplies & Components,"Davidson, North Carolina",2020-03-03,1699150.0,1859
599,IR,2010-11-17,NaN,Ingersoll Rand,Industrials,Industrial Machinery & Supplies & Components,"Davidson, North Carolina",2020-03-03,1699150.0,1859
609,JBL,2001-01-30,2014-11-05,Jabil,Information Technology,Electronic Manufacturing Services,"St. Petersburg, Florida",2023-12-18,898293.0,1966
610,JBL,2023-10-18,NaN,Jabil,Information Technology,Electronic Manufacturing Services,"St. Petersburg, Florida",2023-12-18,898293.0,1966
630,KDP,2008-10-07,2018-07-02,Keurig Dr Pepper,Consumer Staples,Soft Drinks & Non-alcoholic Beverages,"Burlington, Massachusetts",2022-06-21,1418135.0,1981
631,KDP,2022-06-21,NaN,Keurig Dr Pepper,Consumer Staples,Soft Drinks & Non-alcoholic Beverages,"Burlington, Massachusetts",2022-06-21,1418135.0,1981
643,KMI,2012-05-25,NaN,Kinder Morgan,Energy,Oil & Gas Storage & Transportation,"Houston, Texas",2012-05-25,1506307.0,1997
642,KMI,2000-12-12,2007-05-31,Kinder Morgan,Energy,Oil & Gas Storage & Transportation,"Houston, Texas",2012-05-25,1506307.0,1997
653,KSU,1999-04-05,2000-07-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
654,KSU,2013-05-24,2021-12-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
661,LDOS,2019-08-09,NaN,Leidos,Industrials,Diversified Support Services,"Reston, Virginia",2019-08-09,1336920.0,1969
660,LDOS,2009-12-21,2013-09-23,Leidos,Industrials,Diversified Support Services,"Reston, Virginia",2019-08-09,1336920.0,1969
719,MEE,2008-06-23,2011-06-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
718,MEE,1996-01-02,2000-12-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN
732,MIR,1997-08-07,2000-06-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
733,MIR,2001-04-03,2003-07-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
773,MXIM,2000-05-10,2007-09-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
774,MXIM,2018-12-03,2021-08-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790,NE,2001-01-16,2009-03-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
791,NE,2011-01-18,2015-07-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
835,OI,2009-01-02,2016-12-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
834,OI,1997-08-04,2000-12-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
837,OKE,1996-01-02,2001-08-30,Oneok,Energy,Oil & Gas Storage & Transportation,"Tulsa, Oklahoma",2010-03-15,1039684.0,1906
838,OKE,2010-03-15,NaN,Oneok,Energy,Oil & Gas Storage & Transportation,"Tulsa, Oklahoma",2010-03-15,1039684.0,1906
862,PCG,1996-01-02,2019-01-18,PG&E Corporation,Utilities,Multi-Utilities,"Oakland, California",2022-10-03,1004980.0,1905
863,PCG,2022-10-03,NaN,PG&E Corporation,Utilities,Multi-Utilities,"Oakland, California",2022-10-03,1004980.0,1905
913,PTC,2021-04-20,NaN,PTC Inc.,Information Technology,Application Software,"Boston, Massachusetts",2021-04-20,857005.0,1985
912,PTC,1997-04-03,2007-01-03,PTC Inc.,Information Technology,Application Software,"Boston, Massachusetts",2021-04-20,857005.0,1985
947,RIG,1999-12-31,2008-12-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN
948,RIG,2013-10-29,2017-07-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1062,TEL,2007-07-02,2009-06-26,TE Connectivity,Information Technology,Electronic Manufacturing Services,"Galway, Ireland",2011-10-17,1385157.0,2007
1063,TEL,2011-10-17,NaN,TE Connectivity,Information Technology,Electronic Manufacturing Services,"Galway, Ireland",2011-10-17,1385157.0,2007
1066,TER,2020-09-21,NaN,Teradyne,Information Technology,Semiconductor Materials & Equipment,"North Reading, Massachusetts",2020-09-21,97210.0,1960
1065,TER,1999-11-15,2013-12-23,Teradyne,Information Technology,Semiconductor Materials & Equipment,"North Reading, Massachusetts",2020-09-21,97210.0,1960
1086,TMUS,2019-07-15,NaN,T-Mobile US,Communication Services,Wireless Telecommunication Services,"Bellevue, Washington",2019-07-15,1283699.0,1994
1085,TMUS,2009-06-30,2013-05-01,T-Mobile US,Communication Services,Wireless Telecommunication Services,"Bellevue, Washington",2019-07-15,1283699.0,1994
1105,TT,2020-03-03,NaN,Trane Technologies,Industrials,Building Products,"Dublin, Ireland",2010-11-17,1466258.0,1871
1104,TT,2002-05-13,2008-06-06,Trane Technologies,Industrials,Building Products,"Dublin, Ireland",2010-11-17,1466258.0,1871

In [25]:
import yfinance as yf

# 티커 객체 생성
ticker_symbol = "AAL"
stock_info = yf.Ticker(ticker_symbol)

# .info 속성으로 모든 기업 정보 가져오기
company_info = stock_info.info

# 결과 출력 (딕셔너리 형태)
# pprint 모듈을 사용하면 더 보기 쉽게 출력됩니다.
import pprint
pprint.pprint(company_info)

# 특정 정보만 가져오기
print(f"\n회사명: {company_info.get('longName')}")
print(f"산업: {company_info.get('industry')}")
print(f"CEO: {company_info.get('fullTimeEmployees')}")

{'52WeekChange': 0.17834389,
 'SandP52WeekChange': 0.18189907,
 'address1': '1 Skyview Drive',
 'ask': 13.76,
 'askSize': 1,
 'auditRisk': 7,
 'averageAnalystRating': '2.2 - Buy',
 'averageDailyVolume10Day': 76518380,
 'averageDailyVolume3Month': 65823022,
 'averageVolume': 65823022,
 'averageVolume10days': 76518380,
 'beta': 1.401,
 'bid': 12.6,
 'bidSize': 15,
 'boardRisk': 1,
 'bookValue': -5.865,
 'city': 'Fort Worth',
 'companyOfficers': [{'age': 60,
                      'exercisedValue': 0,
                      'fiscalYear': 2024,
                      'maxAge': 1,
                      'name': 'Mr. Robert D. Isom Jr.',
                      'title': 'CEO, President & Director',
                      'totalPay': 4360843,
                      'unexercisedValue': 0,
                      'yearBorn': 1964},
                     {'age': 49,
                      'exercisedValue': 0,
                      'fiscalYear': 2024,
                      'maxAge': 1,
                      'name': 'Mr. Devon E. May',
                      'title': 'Executive VP & CFO',
                      'totalPay': 1959531,
                      'unexercisedValue': 0,
                      'yearBorn': 1975},
                     {'age': 59,
                      'exercisedValue': 0,
                      'fiscalYear': 2024,
                      'maxAge': 1,
                      'name': 'Mr. David G. Seymour',
                      'title': 'Executive VP & COO',
                      'totalPay': 1929898,
                      'unexercisedValue': 0,
                      'yearBorn': 1965},
                     {'age': 68,
                      'exercisedValue': 0,
                      'fiscalYear': 2024,
                      'maxAge': 1,
                      'name': 'Mr. Stephen L. Johnson J.D.',
                      'title': 'Chief Strategy Officer & Vice Chair',
                      'totalPay': 2389572,
                      'unexercisedValue': 0,
                      'yearBorn': 1956},
                     {'exercisedValue': 0,
                      'fiscalYear': 2024,
                      'maxAge': 1,
                      'name': 'Mr. Ganesh  Jayaram',
                      'title': 'Executive VP and Chief Digital & Information '
                               'Officer',
                      'unexercisedValue': 0},
                     {'exercisedValue': 0,
                      'fiscalYear': 2024,
                      'maxAge': 1,
                      'name': 'Abriell  Jackson',
                      'title': 'Managing Director of Investor Relations',
                      'unexercisedValue': 0},
                     {'exercisedValue': 0,
                      'fiscalYear': 2024,
                      'maxAge': 1,
                      'name': 'Mr. Anthony J. Richmond J.D.',
                      'title': 'Executive VP of Corporate Affairs & Chief '
                               'Legal Officer',
                      'unexercisedValue': 0},
                     {'exercisedValue': 0,
                      'fiscalYear': 2024,
                      'maxAge': 1,
                      'name': 'Mr. Ronald J. Defeo',
                      'title': 'EVP of Communications and Marketing & Chief '
                               'Communications Officer',
                      'unexercisedValue': 0},
                     {'exercisedValue': 0,
                      'fiscalYear': 2024,
                      'maxAge': 1,
                      'name': 'Ms. Mecole  Brown',
                      'title': 'Chief People Officer',
                      'unexercisedValue': 0},
                     {'exercisedValue': 0,
                      'fiscalYear': 2024,
                      'maxAge': 1,
                      'name': 'Mr. Bruce  Wark',
                      'title': 'Senior VP & Deputy General Counsel',
                      'unexercisedValue': 0}],
 'compensationAsOfEpochDate': 1735603200,
 'compensationRisk': 3,
 'corporateActions': [],
 'country': 'United States',
 'cryptoTradeable': False,
 'currency': 'USD',
 'currentPrice': 12.95,
 'currentRatio': 0.585,
 'customPriceAlertConfidence': 'HIGH',
 'dateShortInterest': 1755216000,
 'dayHigh': 13.22,
 'dayLow': 12.89,
 'displayName': 'American Airlines',
 'dividendDate': 1582070400,
 'earningsCallTimestampEnd': 1753360200,
 'earningsCallTimestampStart': 1753360200,
 'earningsGrowth': -0.1,
 'earningsQuarterlyGrowth': -0.165,
 'earningsTimestamp': 1753360200,
 'earningsTimestampEnd': 1761222600,
 'earningsTimestampStart': 1761222600,
 'ebitda': 5107999744,
 'ebitdaMargins': 0.094160005,
 'enterpriseToEbitda': 7.277,
 'enterpriseToRevenue': 0.685,
 'enterpriseValue': 37172785152,
 'epsCurrentYear': 0.42561,
 'epsForward': 2.02,
 'epsTrailingTwelveMonths': 0.84,
 'esgPopulated': False,
 'exDividendDate': 1580774400,
 'exchange': 'NMS',
 'exchangeDataDelayedBy': 0,
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'executiveTeam': [],
 'fiftyDayAverage': 12.3002,
 'fiftyDayAverageChange': 0.64979935,
 'fiftyDayAverageChangePercent': 0.052828353,
 'fiftyTwoWeekChangePercent': 17.834389,
 'fiftyTwoWeekHigh': 19.1,
 'fiftyTwoWeekHighChange': -6.1500006,
 'fiftyTwoWeekHighChangePercent': -0.32198957,
 'fiftyTwoWeekLow': 8.5,
 'fiftyTwoWeekLowChange': 4.45,
 'fiftyTwoWeekLowChangePercent': 0.5235294,
 'fiftyTwoWeekRange': '8.5 - 19.1',
 'financialCurrency': 'USD',
 'firstTradeDateMilliseconds': 1127827800000,
 'fiveYearAvgDividendYield': 1.27,
 'floatShares': 653243729,
 'forwardEps': 2.02,
 'forwardPE': 6.410891,
 'freeCashflow': 579500032,
 'fullExchangeName': 'NasdaqGS',
 'fullTimeEmployees': 138100,
 'gmtOffSetMilliseconds': -14400000,
 'governanceEpochDate': 1756684800,
 'grossMargins': 0.24521999,
 'grossProfits': 13303000064,
 'hasPrePostMarketData': True,
 'heldPercentInsiders': 0.01539,
 'heldPercentInstitutions': 0.64892995,
 'impliedSharesOutstanding': 659828992,
 'industry': 'Airlines',
 'industryDisp': 'Airlines',
 'industryKey': 'airlines',
 'isEarningsDateEstimate': True,
 'language': 'en-US',
 'lastDividendDate': 1580774400,
 'lastDividendValue': 0.1,
 'lastFiscalYearEnd': 1735603200,
 'longBusinessSummary': 'American Airlines Group Inc., through its '
                        'subsidiaries, operates as a network air carrier in '
                        'the United States, Latin America, Atlantic, and '
                        'Pacific. The company provides scheduled air '
                        'transportation services for passengers and cargo '
                        'through its hubs in Charlotte, Chicago, Dallas/Fort '
                        'Worth, Los Angeles, Miami, New York, Philadelphia, '
                        'Phoenix, and Washington, D.C., as well as through '
                        'partner gateways in London, Doha, Madrid, '
                        'Seattle/Tacoma, Sydney, and Tokyo. It also operates a '
                        'mainline fleet of 977 aircraft. The company was '
                        'formerly known as AMR Corporation and changed its '
                        'name to American Airlines Group Inc. in December '
                        '2013. American Airlines Group Inc. was founded in '
                        '1926 and is headquartered in Fort Worth, Texas.',
 'longName': 'American Airlines Group Inc.',
 'market': 'us_market',
 'marketCap': 8544785408,
 'marketState': 'POSTPOST',
 'maxAge': 86400,
 'messageBoardId': 'finmb_168569',
 'mostRecentQuarter': 1751241600,
 'netIncomeToCommon': 567000000,
 'nextFiscalYearEnd': 1767139200,
 'numberOfAnalystOpinions': 20,
 'open': 13.07,
 'operatingCashflow': 4094000128,
 'operatingMargins': 0.08289,
 'overallRisk': 2,
 'payoutRatio': 0.0,
 'phone': '682 278 9000',
 'postMarketChange': 0.0,
 'postMarketChangePercent': 0.0,
 'postMarketPrice': 12.95,
 'postMarketTime': 1757375971,
 'previousClose': 13.08,
 'priceEpsCurrentYear': 30.426916,
 'priceHint': 2,
 'priceToBook': -2.2080138,
 'priceToSalesTrailing12Months': 0.15750757,
 'profitMargins': 0.01045,
 'quickRatio': 0.412,
 'quoteSourceName': 'Nasdaq Real Time Price',
 'quoteType': 'EQUITY',
 'recommendationKey': 'buy',
 'recommendationMean': 2.22727,
 'region': 'US',
 'regularMarketChange': -0.13,
 'regularMarketChangePercent': -0.993885,
 'regularMarketDayHigh': 13.22,
 'regularMarketDayLow': 12.89,
 'regularMarketDayRange': '12.89 - 13.22',
 'regularMarketOpen': 13.07,
 'regularMarketPreviousClose': 13.08,
 'regularMarketPrice': 12.95,
 'regularMarketTime': 1757361601,
 'regularMarketVolume': 88960108,
 'returnOnAssets': 0.027999999,
 'revenueGrowth': 0.004,
 'revenuePerShare': 82.379,
 'sector': 'Industrials',
 'sectorDisp': 'Industrials',
 'sectorKey': 'industrials',
 'shareHolderRightsRisk': 4,
 'sharesOutstanding': 659828992,
 'sharesPercentSharesOut': 0.0986,
 'sharesShort': 65052871,
 'sharesShortPreviousMonthDate': 1752537600,
 'sharesShortPriorMonth': 66230607,
 'shortName': 'American Airlines Group, Inc.',
 'shortPercentOfFloat': 0.0992,
 'shortRatio': 0.95,
 'sourceInterval': 15,
 'state': 'TX',
 'symbol': 'AAL',
 'targetHighPrice': 20.0,
 'targetLowPrice': 9.0,
 'targetMeanPrice': 13.43,
 'targetMedianPrice': 13.0,
 'totalCash': 8573000192,
 'totalCashPerShare': 12.993,
 'totalDebt': 37200998400,
 'totalRevenue': 54250000384,
 'tradeable': False,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'trailingEps': 0.84,
 'trailingPE': 15.416667,
 'trailingPegRatio': 0.2408,
 'triggerable': True,
 'twoHundredDayAverage': 13.21485,
 'twoHundredDayAverageChange': -0.26485062,
 'twoHundredDayAverageChangePercent': -0.020041892,
 'typeDisp': 'Equity',
 'volume': 88960108,
 'website': 'https://www.aa.com',
 'zip': '76155'}

회사명: American Airlines Group Inc.
산업: Airlines
CEO: 138100

In [26]:
company_info

{'address1': '1 Skyview Drive',
 'city': 'Fort Worth',
 'state': 'TX',
 'zip': '76155',
 'country': 'United States',
 'phone': '682 278 9000',
 'website': 'https://www.aa.com',
 'industry': 'Airlines',
 'industryKey': 'airlines',
 'industryDisp': 'Airlines',
 'sector': 'Industrials',
 'sectorKey': 'industrials',
 'sectorDisp': 'Industrials',
 'longBusinessSummary': 'American Airlines Group Inc., through its subsidiaries, operates as a network air carrier in the United States, Latin America, Atlantic, and Pacific. The company provides scheduled air transportation services for passengers and cargo through its hubs in Charlotte, Chicago, Dallas/Fort Worth, Los Angeles, Miami, New York, Philadelphia, Phoenix, and Washington, D.C., as well as through partner gateways in London, Doha, Madrid, Seattle/Tacoma, Sydney, and Tokyo. It also operates a mainline fleet of 977 aircraft. The company was formerly known as AMR Corporation and changed its name to American Airlines Group Inc. in December 2013. American Airlines Group Inc. was founded in 1926 and is headquartered in Fort Worth, Texas.',
 'fullTimeEmployees': 138100,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Robert D. Isom Jr.',
   'age': 60,
   'title': 'CEO, President & Director',
   'yearBorn': 1964,
   'fiscalYear': 2024,
   'totalPay': 4360843,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Devon E. May',
   'age': 49,
   'title': 'Executive VP & CFO',
   'yearBorn': 1975,
   'fiscalYear': 2024,
   'totalPay': 1959531,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. David G. Seymour',
   'age': 59,
   'title': 'Executive VP & COO',
   'yearBorn': 1965,
   'fiscalYear': 2024,
   'totalPay': 1929898,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Stephen L. Johnson J.D.',
   'age': 68,
   'title': 'Chief Strategy Officer & Vice Chair',
   'yearBorn': 1956,
   'fiscalYear': 2024,
   'totalPay': 2389572,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ganesh  Jayaram',
   'title': 'Executive VP and Chief Digital & Information Officer',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Abriell  Jackson',
   'title': 'Managing Director of Investor Relations',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Anthony J. Richmond J.D.',
   'title': 'Executive VP of Corporate Affairs & Chief Legal Officer',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ronald J. Defeo',
   'title': 'EVP of Communications and Marketing & Chief Communications Officer',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Mecole  Brown',
   'title': 'Chief People Officer',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bruce  Wark',
   'title': 'Senior VP & Deputy General Counsel',
   'fiscalYear': 2024,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 1,
 'compensationRisk': 3,
 'shareHolderRightsRisk': 4,
 'overallRisk': 2,
 'governanceEpochDate': 1756684800,
 'compensationAsOfEpochDate': 1735603200,
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 13.08,
 'open': 13.07,
 'dayLow': 12.89,
 'dayHigh': 13.22,
 'regularMarketPreviousClose': 13.08,
 'regularMarketOpen': 13.07,
 'regularMarketDayLow': 12.89,
 'regularMarketDayHigh': 13.22,
 'exDividendDate': 1580774400,
 'payoutRatio': 0.0,
 'fiveYearAvgDividendYield': 1.27,
 'beta': 1.401,
 'trailingPE': 15.416667,
 'forwardPE': 6.410891,
 'volume': 88960108,
 'regularMarketVolume': 88960108,
 'averageVolume': 65823022,
 'averageVolume10days': 76518380,
 'averageDailyVolume10Day': 76518380,
 'bid': 12.6,
 'ask': 13.76,
 'bidSize': 15,
 'askSize': 1,
 'marketCap': 8544785408,
 'fiftyTwoWeekLow': 8.5,
 'fiftyTwoWeekHigh': 19.1,
 'priceToSalesTrailing12Months': 0.15750757,
 'fiftyDayAverage': 12.3002,
 'twoHundredDayAverage': 13.21485,
 'trailingAnnualDividendRate': 0.0,
 'trailingAnnualDividendYield': 0.0,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 37172785152,
 'profitMargins': 0.01045,
 'floatShares': 653243729,
 'sharesOutstanding': 659828992,
 'sharesShort': 65052871,
 'sharesShortPriorMonth': 66230607,
 'sharesShortPreviousMonthDate': 1752537600,
 'dateShortInterest': 1755216000,
 'sharesPercentSharesOut': 0.0986,
 'heldPercentInsiders': 0.01539,
 'heldPercentInstitutions': 0.64892995,
 'shortRatio': 0.95,
 'shortPercentOfFloat': 0.0992,
 'impliedSharesOutstanding': 659828992,
 'bookValue': -5.865,
 'lastFiscalYearEnd': 1735603200,
 'nextFiscalYearEnd': 1767139200,
 'mostRecentQuarter': 1751241600,
 'earningsQuarterlyGrowth': -0.165,
 'netIncomeToCommon': 567000000,
 'trailingEps': 0.84,
 'forwardEps': 2.02,
 'enterpriseToRevenue': 0.685,
 'enterpriseToEbitda': 7.277,
 '52WeekChange': 0.17834389,
 'SandP52WeekChange': 0.18189907,
 'lastDividendValue': 0.1,
 'lastDividendDate': 1580774400,
 'quoteType': 'EQUITY',
 'currentPrice': 12.95,
 'targetHighPrice': 20.0,
 'targetLowPrice': 9.0,
 'targetMeanPrice': 13.43,
 'targetMedianPrice': 13.0,
 'recommendationMean': 2.22727,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 20,
 'totalCash': 8573000192,
 'totalCashPerShare': 12.993,
 'ebitda': 5107999744,
 'totalDebt': 37200998400,
 'quickRatio': 0.412,
 'currentRatio': 0.585,
 'totalRevenue': 54250000384,
 'revenuePerShare': 82.379,
 'returnOnAssets': 0.027999999,
 'grossProfits': 13303000064,
 'freeCashflow': 579500032,
 'operatingCashflow': 4094000128,
 'earningsGrowth': -0.1,
 'revenueGrowth': 0.004,
 'grossMargins': 0.24521999,
 'ebitdaMargins': 0.094160005,
 'operatingMargins': 0.08289,
 'financialCurrency': 'USD',
 'symbol': 'AAL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'shortName': 'American Airlines Group, Inc.',
 'longName': 'American Airlines Group Inc.',
 'marketState': 'POSTPOST',
 'epsTrailingTwelveMonths': 0.84,
 'epsForward': 2.02,
 'epsCurrentYear': 0.42561,
 'priceEpsCurrentYear': 30.426916,
 'fiftyDayAverageChange': 0.64979935,
 'fiftyDayAverageChangePercent': 0.052828353,
 'twoHundredDayAverageChange': -0.26485062,
 'twoHundredDayAverageChangePercent': -0.020041892,
 'priceToBook': -2.2080138,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.2 - Buy',
 'cryptoTradeable': False,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_168569',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'gmtOffSetMilliseconds': -14400000,
 'market': 'us_market',
 'esgPopulated': False,
 'corporateActions': [],
 'postMarketTime': 1757375971,
 'regularMarketTime': 1757361601,
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 1127827800000,
 'postMarketChangePercent': 0.0,
 'postMarketPrice': 12.95,
 'postMarketChange': 0.0,
 'regularMarketChange': -0.13,
 'regularMarketDayRange': '12.89 - 13.22',
 'regularMarketChangePercent': -0.993885,
 'regularMarketPrice': 12.95,
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 65823022,
 'fiftyTwoWeekLowChange': 4.45,
 'fiftyTwoWeekLowChangePercent': 0.5235294,
 'fiftyTwoWeekRange': '8.5 - 19.1',
 'fiftyTwoWeekHighChange': -6.1500006,
 'fiftyTwoWeekHighChangePercent': -0.32198957,
 'fiftyTwoWeekChangePercent': 17.834389,
 'dividendDate': 1582070400,
 'earningsTimestamp': 1753360200,
 'earningsTimestampStart': 1761222600,
 'earningsTimestampEnd': 1761222600,
 'earningsCallTimestampStart': 1753360200,
 'earningsCallTimestampEnd': 1753360200,
 'isEarningsDateEstimate': True,
 'displayName': 'American Airlines',
 'trailingPegRatio': 0.2408}

In [33]:
import yfinance as yf
import json
import pprint

# 티커 객체 생성
ticker_symbol = "PXD"
stock_info = yf.Ticker(ticker_symbol)

# .info 속성으로 기업 정보 가져오기
company_info = stock_info.info

# 파일로 저장하기 (JSON 형식으로 저장하면 나중에 읽기 편합니다)
file_path = f"{ticker_symbol}_info.json"

with open(file_path, "w", encoding="utf-8") as f:
    # pprint.pformat()을 사용하면 문자열 형태로 포맷팅하여 파일에 쓸 수 있습니다.
    pprint_string = pprint.pformat(company_info, indent=4)
    f.write(pprint_string)

print(f"모든 정보가 '{file_path}' 파일에 저장되었습니다.")

# 또는 JSON 모듈을 직접 사용해도 됩니다.
# with open(f"{ticker_symbol}_info_json.json", "w", encoding="utf-8") as f:
#     json.dump(company_info, f, indent=4, ensure_ascii=False)

모든 정보가 'PXD_info.json' 파일에 저장되었습니다.

In [32]:
company_info['firstTradeDateMilliseconds']

642432600000

In [34]:
pxd = yf.download('PXD', start='2020-01-01', end='2025-09-09')

C:\Users\fzaca\AppData\Local\Temp\ipykernel_50996\1897196093.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  pxd = yf.download('PXD', start='2020-01-01', end='2025-09-09')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['PXD']: YFTzMissingError('possibly delisted; no timezone found')

In [35]:
pxd

Empty DataFrame
Columns: [(Adj Close, PXD), (Close, PXD), (High, PXD), (Low, PXD), (Open, PXD), (Volume, PXD)]
Index: []

In [36]:
mxim = yf.download('MXIM', start='2006-01-01', end='207-09-09')
mxim

C:\Users\fzaca\AppData\Local\Temp\ipykernel_50996\2558544447.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  mxim = yf.download('MXIM', start='2006-01-01', end='207-09-09')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['MXIM']: YFTzMissingError('possibly delisted; no timezone found')

Empty DataFrame
Columns: [(Adj Close, MXIM), (Close, MXIM), (High, MXIM), (Low, MXIM), (Open, MXIM), (Volume, MXIM)]
Index: []